env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
language: node_js
node_js:
  - "6.1"
services:
  - redis-server
install:
  - mkdir ~/bin
  - wget -O ~/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
  - chmod 755 ~/bin/lein
  - PATH=$PATH:~/bin
  - lein
  - lein deps

script:
  - lein do cljsbuild once moomoo-frontend-release, clean, doo node test-frontend once
